### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by fexed** [fexed/Pinball-on-Android#4]

**Comment by OpenRift412** [comment]
Here's a recording of the main background theme on my Roland SC-55 in case you don't want to use Android's native MIDI playback: [Google Drive ](https://drive.google.com/file/d/1TIcTBPvxJKU_cIee9SKJfihzqfoS-Txt/view?usp=sharing)

**Comment by jrdiver** [comment]
It might be a more faithful reproduction to record it with the windows media player built in Midi player instead of the Roland since I would make a guess that the vast majority of users listened with that Midi profile

**Comment by OpenRift412** [comment]
> It might be a more faithful reproduction to record it with the windows media player built in Midi player instead of the Roland since I would make a guess that the vast majority of users listened with that Midi profile

Well the MIDI bank that Windows comes with by default is essentially a bit-crushed version of the SC-55's soundbank, so it's probably a better quality experience to have recorded it with the Roland synth instead.

**Comment by nzgamer41** [comment]
I don't know how much you've looked into it but the issue I saw was that SDL Mixer couldn't find a playback device for midi, I tried forcing Timidity but that didn't work, so I figure it's something to do with how SDL Mixer is being built

**Comment by Danindanis** [comment]
Another point to consider is the songs from the original version of maxis.  actually there are 3 songs.  I know that in the xp version it doesn't have that.  But it's a good idea.  A good thing is to have the option to use classic sound and one with better soundfonts.

**Comment by Yonle** [comment]
Will keep this here who knows this may be useful.

From: Fluidsynth with built in soundfont (i guess?)
https://dl.uploadgram.me/63abe53f6f320h.ogg?raw

**Comment by Yonle** [comment]
I'ma leave this here, who knows this may be useful

From original `PINBALL.MID` with fluidsynth default soundfont (I guess, or is it? Anyways, This sounds good for me): https://web.archive.org/web/20221228065155if_/https://0x0.st/o5FO.ogg

**Comment by lokustus** [comment]
Hi everybody!
I'm a completely noob when it comes to Android Developing and stuff, anyway, today I've tried some basic things but I can't get them totally done.

To get the music in the game, I've already tried converting the PINBALL.MID file to .WAV; Renaming the PINBALL.MID word in every document that has it (I don't remember which file missed to declare the Pinball.wav new file but also added the line); Modifying the WAVEMIX.INF file to set "Remix" and "GoodWavePos" as enabled in every scenario;  But still with no music. (everything done in APK Editor Studio for Windows).

Diggin' up, I've even messed up trying to add the Kotlin SoundPool to the project but then I realized that works over Java LOL.

So, my suggestion is the next one:
What if we try the following and most basic thing? (supposing that has not been tried yet).

1. Into the app/res/raw folder, put the music file but converted to .mp3 for more compatibility and to not make the apk bigger.
2. Into the app/Java/com.fexed.spacecadetpinball/MainActivity.java file, add the following line codes after the "@Override" part:

        MediaPlayer Pinball= MediaPlayer.create(MainActivity.this,R.raw.Pinball);
        Pinball.start();
(refer to attachments for better understanding).

If you ask, I've already tried to do it in Android Studio but, unfortunately, I can't build the APK to test it. I get some errors regarding the CMakeLists.txt file and the Google-Services.json file that is missing, I can't figure out how to make it; Also, tried using the "gradlew.bat" file but got another error regarding my JDK Version and well, I can't imagine how to solve it.

Anyway, if somebody could try out the thing I've listed above, I think it would be interesting to see if something happens.

Greetings to all of you and thanx for reading if someone does it :)
-------------------------------------------------------------------
![MainActivity_FileChanges](https://user-images.githubusercontent.com/100889970/224905690-2dce2a03-f3ff-43c2-8fad-7db457ecf4c3.PNG)

![Raw_Pinballmp3File](https://user-images.githubusercontent.com/100889970/224905973-2a7ffdee-53c3-44a5-8bcd-896ce9f3ee7d.PNG)

![Maybe_RedeclareTheseFiles](https://user-images.githubusercontent.com/100889970/224906138-8b8aecea-70b7-4bc0-97ec-d2c6db968018.PNG)
(Maybe, the files shown in this image, shall be re-declared as well to "Pinball.mp3" instead of PINBALL.MID, just in case).
_________________________________________________________________
[Pinball.mp3 file](https://drive.google.com/file/d/1VlzHpNu6nQUKnG0ukEUhzVesdBKLK7Yw/view?usp=share_link)

p.s. I know the song sounds like with Reverb, remember, it's a direct conversion, anyway, I haven't tested how it sounds in cellphones.

**Comment by fexed** [comment]
Thanks @lokustus ! I will try this suggestion asap!

**Comment by lokustus** [comment]
> Thanks @lokustus ! I will try this suggestion asap!

Thanx to you for givin' it a try :)
So glad to help, bro! @fexed
